### ISSUE TITLE
Adapt to meinBerlin Changes

### ISSUE THREAD

**Issue by kleingeist** [liqd/a4-product#55]
- [ ] overwrite datetime template liqd/a4-meinberlin#927
- [x] Make testuser username unique liqd/a4-meinberlin#978
- [x] Switch to babel-env liqd/a4-meinberlin#986
- [x] project tile image preview in create modal ( liqd/a4-meinberlin#815 )
- [x] refactor alert styling https://github.com/liqd/a4-meinberlin/pull/1008

**Comment by kleingeist** [comment]
removed from the milestone alpha 1 as the datetime template is not that important (not shown to users)

**Comment by fuzzylogic2000** [comment]
Looks fine now! And we never have to do that again!
